name: value_selectable
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  