name: value_selectable
description: "A Flutter package that provides computed values for `ValueNotifier`, inspired by the Selectors from Recoil."

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  